name: Deploy to Heroku (backend)

on:
  push:
    branches:
      - master
    paths:
      - "server/**"
      - ".github/workflows/backend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Add heroku remote for backend
        run: git remote add heroku-backend https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_BACKEND_NAME }}.git
      #- name: Deploy backend to heroku
      #  run: git push heroku-backend `git subtree split --prefix server master`:refs/heads/master --force
      - name: Filter for server and types files
        run: git filter-branch --index-filter 'git rm --cached -qr --ignore unmatch -- . && git reset -q $GIT_COMMIT -- server/\* types' --prune-empty -- --all
      - name: Deploy to heroku
        run: git push heroku-backend master --force
